# network architecture
# encoder related
linear_units: 1024  # the number of units of position-wise feed forward

collate_conf:
    wav_aug: true
    wav_aug_conf:
        length: 2 #second
        add_rev: true
        add_noise: true
    # waveform level config
    feature_extraction_conf:
        feature_type: 'mfcc'
        mel_bins: 40
        frame_shift: 10
        frame_length: 25
        using_pitch: false
        wav_dither: 0.1
        high-freq: -400
        low-freq: 40

# dataset related
dataset_conf:
    batch_size: 128

grad_clip: 5
accum_grad: 4
max_epoch: 100
log_interval: 100

optim: adam
optim_conf:
    lr: 0.001
    gamma: 0.97
